### ISSUE TITLE
Import syntax error with losses/_rpn.py

### ISSUE THREAD

**Issue by jrosebr1** [broadinstitute/keras-rcnn#140]
I was playing around with keras-rcnn using Ubuntu and Python 3.4. From my Python shell:

<pre>$ python
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from keras_rcnn.models import RCNN
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adrian/keras-rcnn/keras_rcnn/models/__init__.py", line 1, in <module>
    from ._rcnn import RCNN
  File "/home/adrian/keras-rcnn/keras_rcnn/models/_rcnn.py", line 10, in <module>
    import keras_rcnn.layers
  File "/home/adrian/keras-rcnn/keras_rcnn/layers/__init__.py", line 1, in <module>
    from .losses import (
  File "/home/adrian/keras-rcnn/keras_rcnn/layers/losses/__init__.py", line 7, in <module>
    from ._rpn import (
  File "/home/adrian/keras-rcnn/keras_rcnn/layers/losses/_rpn.py", line 86
    return {**super(RPN, self).get_config(), **configuration}
             ^
SyntaxError: invalid syntax</pre>

Since this is a syntax error perhaps I suppose I should be testing with a different version of Python?

**Comment by jhung0** [comment]
Hmm not sure if 3.4 works. We use 3.6

**Comment by jrosebr1** [comment]
Thanks, I will give that a try.

**Comment by milani** [comment]
@jhung0 3.5.3 works fine.

**Comment by milani** [comment]
@chituma110 With new commits, It needs at least python 3.6 to run.
