### ISSUE TITLE
can't have a batch_size bigger than 1

### ISSUE THREAD

**Issue by shantanukarve** [broadinstitute/keras-rcnn#156]
When I try the README  code snippet but adding a batch_size parameter 
```
...
generator = generator.flow(training, classes, batch_size=2)
(target_bounding_boxes, target_image, target_scores, _), _ = generator.next()
...
```
I get this TraceBack
```
Traceback (most recent call last):

  File "<ipython-input-2-2786152bf86a>", line 1, in <module>
    (target_bounding_boxes, target_image, target_scores, _), _ = generator.next()

  File "/home/shantanu/kaggle/dsb/keras-rcnn/keras_rcnn/preprocessing/_object_detection.py", line 81, in next
    [boxes, images, labels, self.metadata], got_one = self._get_batches_of_transformed_samples(selection)

  File "/home/shantanu/kaggle/dsb/keras-rcnn/keras_rcnn/preprocessing/_object_detection.py", line 154, in _get_batches_of_transformed_samples
    boxes = numpy.append(boxes, [[box]], axis=1)

  File "/home/shantanu/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 5147, in append
    return concatenate((arr, values), axis=axis)

ValueError: all the input array dimensions except for the concatenation axis must match exactly
```

**Comment by jhung0** [comment]
yes, it needs to be 1

**Comment by shantanukarve** [comment]
yes, I figured the fix is going to be complex, its not just a matter of generalizing this line 
  boxes = numpy.append(boxes, [[box]], axis=1)
to handle batch-size "properly".  From my short investigation, the hard problem is that different images in a batch can have different number of boxes so its not just a matter of handling a boxes(batch_size, num_of_boxes-for-that-image, 4)  array so need to go to lists ?
